version: "3.3"
services:
  mongodb:
    image: mongo:3.5
    volumes:
      - type: bind
        source: ./data/db
        target: /data/db
  web:
    image: branchzero/yapi:1.2.4
    command: /bin/bash -c "[ ! -e init.lock ] && npm run install-server; npm run start"
    links:
      - mongodb:mongodb
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: ./config.json
        target: /home/yapi/config.json